
package todoserversoap.app;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ToDoServerService", targetNamespace = "http://app.toDoServerSOAP/", wsdlLocation = "http://localhost:8081/toDoSOAP?wsdl")
public class ToDoServerService
    extends Service
{

    private final static URL TODOSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException TODOSERVERSERVICE_EXCEPTION;
    private final static QName TODOSERVERSERVICE_QNAME = new QName("http://app.toDoServerSOAP/", "ToDoServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/toDoSOAP?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TODOSERVERSERVICE_WSDL_LOCATION = url;
        TODOSERVERSERVICE_EXCEPTION = e;
    }

    public ToDoServerService() {
        super(__getWsdlLocation(), TODOSERVERSERVICE_QNAME);
    }

    public ToDoServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ToDoServer
     */
    @WebEndpoint(name = "ToDoServerPort")
    public ToDoServer getToDoServerPort() {
        return super.getPort(new QName("http://app.toDoServerSOAP/", "ToDoServerPort"), ToDoServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ToDoServer
     */
    @WebEndpoint(name = "ToDoServerPort")
    public ToDoServer getToDoServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://app.toDoServerSOAP/", "ToDoServerPort"), ToDoServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TODOSERVERSERVICE_EXCEPTION!= null) {
            throw TODOSERVERSERVICE_EXCEPTION;
        }
        return TODOSERVERSERVICE_WSDL_LOCATION;
    }

}
